default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  checkout_timeout: 20
  reaping_frequency: 30

test:
  <<: *default
  host: localhost
  database: instagram_test

