process_photos:
  cron: "* * * * *"
  class: "PhotoAnalysisSchedulerWorker"
  queue: analysis

discovery:
  cron: "*/5 * * * *" # execute at every 60 minutes
  class: "DiscoveryWorker"
  queue: discovery

like_photos:
  cron: "*/1 * * * *"
  class: "PhotoLikerWorker"
  queue: instagram_api

follow_users:
    cron: "*/60 * * * *"
    class: "ScheduleFollowsWorker"
    queue: follows
