---
:concurrency: 5
:verbose: false
:logfile: ./log/sidekiq.log
:pidfile: tmp/pids/sidekiq.pid
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - default
  - creations
  - analysis
  - instagram_api
  - scrape_photos