---
:concurrency: 10
:pidfile: tmp/pids/sidekiq.pid
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - default
  - discovery
  - follows
  - creations
  - analysis
  - instagram_api
  - scrape_photos
